# It's good to set for conda strict channel priority:
# $ conda config --set channel_priority strict
# This file may be used to create an environment using:
# $ conda env create --name <env> --file <this file>
# $ e.g. conda env create --name g4rt --file conda_env.yml
# Or for update already existing environment:
# $ conda env update --file conda_env.yml
channels:
  - conda-forge
dependencies:
  - python=3.11.3
  - root=6.28.0
  - xerces-c=3.2.4
  - pybind11=2.10.4
  - libffi=3.4.2
  - gxx=11.3.0
  - spdlog=1.12.0
  - gtest=1.14.0
  - fmt=9.1.0
  - pip
  - pip:
    - "git+https://git.plgrid.pl/scm/tnd3d/pydose3d.git@develop#egg=pydose3d"